### ISSUE TITLE
Can't load AusMap Plugin QGIS 2.18.5

### ISSUE THREAD

**Issue by roryhall** [WMS-Engineering/AusMap#4]
Couldn't load plugin AusMap-master due to an error when calling its classFactory() method

**Comment by Dan-Knott** [comment]
Hi could you give me a little bit more information, QGIS version and operating system

**Comment by roryhall** [comment]
My apologies I should of thought of that. 
QGIS version 2.18.5
Compiled against Qt 4.8.5
Compiled against GDAL/OGR 2.1.3
Compiled against GEOS 3.5.0-CAPI-1.9.0
PostgreSQL Client Version 9.2.4
QWT Version 5.2.3
QScintilla2 Version 2.7.2

QGIS code revision 140a01f
Running against Qt 4.8.5
Running against GDAL/OGR 2.1.3
Running against GEOS 3.5.0-CAPI-1.9.0 r4084
SpatiaLite Version 4.3.0
PROJ.4 Version 493

Running on Windows 7 Enterprise 64 Bit Service Pack1

**Comment by Dan-Knott** [comment]
Is the error occurring when you try to install AusMap from the Plugin Manager?

**Comment by anemdr** [comment]
Dan 
Same story here, cannot install from Plugin Manager.  Get message
The plugin is broken.  Python said: **2**

Running on Ubuntu 16.04.
QGIS version | 2.18.11 | QGIS code revision | 29548e7
Compiled against Qt | 4.8.7 | Running against Qt | 4.8.7
Compiled against GDAL/OGR | 1.11.3 | Running against GDAL/OGR | 1.11.3
Compiled against GEOS | 3.5.0-CAPI-1.9.0 | Running against GEOS | 3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version | 9.5.2 | SpatiaLite Version | 4.3.0a
QWT Version | 5.2.3 | PROJ.4 Version | 492
QScintilla2 Version | 2.9.1 |

**Comment by Dan-Knott** [comment]
When opening qgis or installing the plugin, are you able to see the stack trace. There may be a button in the error message bar and it will have a window.
![image](https://user-images.githubusercontent.com/29566573/30623736-df8a3dac-9dfc-11e7-882a-1068096f3d4b.png)
if you could send em the text there i should be able to find the problem

**Comment by roryhall** [comment]
I cant actually get past our proxy server to install, so I manually copied the plugin into the plugins folder. It shows up in the plugin manager (with the error). I have used the same methodology to install several other plugins and they all work ok.

**Comment by Dan-Knott** [comment]
AusMap requires an open internet connection on startup to download the latest list of layers. I think this connection must be blocked. I know the library i use for that web connection is a bit old, and can be a bit dodgy with proxies. I'll try updating to the officially supported QgsNetworkAccessManager in the next release.

Until then though, if you can any further information from QGIS on the error we might be able to find a workaround.

**Comment by roryhall** [comment]
I have just retried this time I get an error that the metadata file is missing. I have connectivity to the internet and consume other web services in Qgis no problems. I will get our proxy settings from IT and give installing via the plugins repository a shot.

**Comment by Drum8** [comment]
I had the same issue...

2017-09-25T10:44:51	1	No contact to the configuration at https://raw.githubusercontent.com/Dan-Knott/AusMap/master/About.htm. Exception: <urlopen error Tunnel connection failed: 407 Proxy Authorization Required>

Works great when the proxy is bypassed.

**Comment by DominiqueTaylor** [comment]
Getting same issue (GQIS 2.18.5 on Windows 7). I have already had IT change my proxy settings so that I could see the plugin list (couldn't see it at all initially) and I have successfully downloaded other plugins, but can't get AusMap. Getting this error script:

Couldn't load plugin AusMap-master due to an error when calling its classFactory() method 

NameError: global name 'local_file_exists' is not defined 
Traceback (most recent call last):
  File "C:/Program Files/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/NelsonD/.qgis2/python/plugins\AusMap-master\__init__.py", line 35, in classFactory
    return AusMap(iface)
  File "C:/Users/NelsonD/.qgis2/python/plugins\AusMap-master\aus_map.py", line 109, in __init__
    self.read_about_page()
  File "C:/Users/NelsonD/.qgis2/python/plugins\AusMap-master\aus_map.py", line 141, in read_about_page
    if not local_file_exists:
NameError: global name 'local_file_exists' is not defined


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.5 Las Palmas, 140a01f

**Comment by WaterModellingSolutions** [comment]
Please now refer to our upgraded version [here](https://plugins.qgis.org/plugins/AusMap/)
